package avpipe

import _ "embed"

// Embedding lib/libavpipe.hash causes Go to rebuild this package whenever the
// C library changes, without requiring `go clean -cache` after `make`.
// The hash file is generated by `make` via: openssl dgst -md5 lib/libavpipe.a
//
//go:embed lib/libavpipe.hash
var _ []byte
